import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const chatbotUrl = process.env.NEXT_PUBLIC_CHATBOT_URL || 'https://portfolio-chatbot-widget.vercel.app';
  
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.CHATBOT_BASE_URL = "${chatbotUrl}";
              window.CHATBOT_TITLE = "Arnob's Assistant";
              window.CHATBOT_GREETING = "👋 How can I help you today?";
              window.CHATBOT_PLACEHOLDER = "Ask about Arnob...";
            `,
          }}
        />
        <script
          src={`${chatbotUrl}/widget.js`}
          async
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
